version: '3.5'

services:
  php-fpm:
    container_name: wholesaler-php
    build:
      dockerfile: docker/php-fpm/Dockerfile
      context: .
    volumes:
      - ./:/app

  nginx:
    container_name: wholesaler-nginx
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8085:80"